spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        # automatically escape SQL reserved keywords
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
